"""Compatibility wrapper for observability logging helpers."""

from bot.observability.error_file_logging import (
    BACKUP_COUNT,
    ERROR_FILE_HANDLER_NAME,
    MAX_BYTES,
    MAX_EXPORT_BYTES,
    LogExport,
    RedactingFormatter,
    _active_error_log_path,
    _collect_secret_values,
    _configured_log_paths,
    _dedupe_paths,
    _find_file_handler,
    _find_named_file_handler,
    _redact,
    apply_persisted_error_file_logging_state,
    build_sanitized_log_exports,
    disable_error_file_logging,
    enable_error_file_logging,
    get_available_log_export_paths,
    is_error_file_logging_enabled,
)
from bot.observability.operational_logging import (
    OPERATIONAL_FILE_HANDLER_NAME,
    OPERATIONAL_LOG_FILE,
    enable_operational_file_logging,
)

__all__ = [
    "BACKUP_COUNT",
    "ERROR_FILE_HANDLER_NAME",
    "MAX_BYTES",
    "MAX_EXPORT_BYTES",
    "OPERATIONAL_FILE_HANDLER_NAME",
    "OPERATIONAL_LOG_FILE",
    "LogExport",
    "RedactingFormatter",
    "_active_error_log_path",
    "_collect_secret_values",
    "_configured_log_paths",
    "_dedupe_paths",
    "_find_file_handler",
    "_find_named_file_handler",
    "_redact",
    "apply_persisted_error_file_logging_state",
    "build_sanitized_log_exports",
    "disable_error_file_logging",
    "enable_error_file_logging",
    "enable_operational_file_logging",
    "get_available_log_export_paths",
    "is_error_file_logging_enabled",
]
